spring:
  application:
    name: stream-listener
  cloud:
    stream:
      bindings:
        input:
          destination: exampleTopic
          content-type: application/json
          group: exampleGroup
        binder:
          zkNodes: localhost
          brokers: localhost
