spring:
  application:
    name: stream-publisher
  cloud:
    stream:
      bindings:
        output:
          destination: exampleTopic
          content-type: application/json
        kafka:
          binder:
           zkNodes: localhost
           brokers: localhost
